# KMeans сравнение центройда с средним арифметическим вектором
KMeans использует для вычисления центройда средний арифметический вектор, ниже приведено доказательство

In [1]:
data = [
    "один два три четыре пять четыре пять два три",
    "пять четыре три два один",
    "три два один пять четыре",
    
    "шесть семь восемь девять десять",
    "девять десять шесть семь восемь",
    "семь восемь восемь девять девять десять",
    
    "кот кошка собака голубь попугай дятел",
    "голубь попугай дятел кот кошка собака",
    "кот кошка попугай дятел собака голубь"
]

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import WhitespaceTokenizer
tokenizer = WhitespaceTokenizer()

tfidf_vectorizer = TfidfVectorizer(
                                   #max_df=3, min_df=2,
                                   tokenizer=tokenizer.tokenize,
                                   ngram_range=(1,3),
                                   )

tfidf = tfidf_vectorizer.fit_transform(data)

In [4]:
from sklearn.cluster import KMeans

num_clusters = 3

km = KMeans(n_clusters=num_clusters)

km.fit(tfidf)

clusters = km.cluster_centers_
labels = km.labels_
labels[:100]

array([1, 1, 1, 0, 0, 0, 2, 2, 2], dtype=int32)

In [29]:
centroid0 = clusters[1]
centroid0

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.26217276,
        0.19455923,  0.11517615,  0.12665173,  0.06332587,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.21566819,  0.06332587,  0.06332587,  0.11517615,
        0.11517615,  0.        ,  0.        ,  0.        ,  0.        ,
        0.26217276,  0.06332587,  0.06332587,  0.21566819,  0.06332587,
        0.11517615,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.26217276,  0.19455923,
        0.19455923,  0.06332587,  0.06332587,  0.26217276,  0.12665173,
        0.06332587,  0.06332587,  0.11517615,  0.11517615,  0.  

In [25]:
mean0 = tfidf[0:3].mean(axis=0)
mean0

matrix([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.26217276,
          0.19455923,  0.11517615,  0.12665173,  0.06332587,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.21566819,  0.06332587,  0.06332587,  0.11517615,
          0.11517615,  0.        ,  0.        ,  0.        ,  0.        ,
          0.26217276,  0.06332587,  0.06332587,  0.21566819,  0.06332587,
          0.11517615,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.26217276,  0.19455923,
          0.19455923,  0.06332587,  0.06332587,  0.26217276,  0.12665173,
          0.06332587,  0.06332587,  0.

In [27]:
from scipy.spatial import distance
distance.cosine(mean0, centroid0)

0.0

In [33]:
distance.cosine(tfidf[3:6].mean(axis=0), clusters[0])

0.0

## Отклонение центройда от единичного вектора

In [34]:
import numpy as np

In [47]:
one = np.empty(72)
one.fill(1)

In [53]:
distance.cosine(clusters[0], one)

0.50484763021797918

In [49]:
distance.cosine(clusters[1], one)

0.46075219567998293

In [50]:
distance.cosine(clusters[2], one)

0.45504554298952427